/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as DashboardRouteRouteImport } from './routes/_dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as DashboardUserIndexRouteImport } from './routes/_dashboard/user/index'
import { Route as DashboardProfileIndexRouteImport } from './routes/_dashboard/profile/index'
import { Route as DashboardProductIndexRouteImport } from './routes/_dashboard/product/index'
import { Route as DashboardCategoryIndexRouteImport } from './routes/_dashboard/category/index'
import { Route as DashboardBundleIndexRouteImport } from './routes/_dashboard/bundle/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as DashboardProductCreateRouteImport } from './routes/_dashboard/product/create'
import { Route as DashboardProductEditIdRouteImport } from './routes/_dashboard/product/edit.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardUserIndexRoute = DashboardUserIndexRouteImport.update({
  id: '/user/',
  path: '/user/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProfileIndexRoute = DashboardProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductIndexRoute = DashboardProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCategoryIndexRoute = DashboardCategoryIndexRouteImport.update({
  id: '/category/',
  path: '/category/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBundleIndexRoute = DashboardBundleIndexRouteImport.update({
  id: '/bundle/',
  path: '/bundle/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductCreateRoute = DashboardProductCreateRouteImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardProductEditIdRoute = DashboardProductEditIdRouteImport.update({
  id: '/product/edit/$id',
  path: '/product/edit/$id',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/upload': typeof ApiUploadRoute
  '/product/create': typeof DashboardProductCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bundle/': typeof DashboardBundleIndexRoute
  '/category/': typeof DashboardCategoryIndexRoute
  '/product/': typeof DashboardProductIndexRoute
  '/profile/': typeof DashboardProfileIndexRoute
  '/user/': typeof DashboardUserIndexRoute
  '/product/edit/$id': typeof DashboardProductEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/api/upload': typeof ApiUploadRoute
  '/product/create': typeof DashboardProductCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/bundle': typeof DashboardBundleIndexRoute
  '/category': typeof DashboardCategoryIndexRoute
  '/product': typeof DashboardProductIndexRoute
  '/profile': typeof DashboardProfileIndexRoute
  '/user': typeof DashboardUserIndexRoute
  '/product/edit/$id': typeof DashboardProductEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dashboard': typeof DashboardRouteRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/api/upload': typeof ApiUploadRoute
  '/_dashboard/product/create': typeof DashboardProductCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_dashboard/bundle/': typeof DashboardBundleIndexRoute
  '/_dashboard/category/': typeof DashboardCategoryIndexRoute
  '/_dashboard/product/': typeof DashboardProductIndexRoute
  '/_dashboard/profile/': typeof DashboardProfileIndexRoute
  '/_dashboard/user/': typeof DashboardUserIndexRoute
  '/_dashboard/product/edit/$id': typeof DashboardProductEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unauthorized'
    | '/sign-in'
    | '/sign-up'
    | '/api/upload'
    | '/product/create'
    | '/api/auth/$'
    | '/bundle/'
    | '/category/'
    | '/product/'
    | '/profile/'
    | '/user/'
    | '/product/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unauthorized'
    | '/sign-in'
    | '/sign-up'
    | '/api/upload'
    | '/product/create'
    | '/api/auth/$'
    | '/bundle'
    | '/category'
    | '/product'
    | '/profile'
    | '/user'
    | '/product/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/unauthorized'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/api/upload'
    | '/_dashboard/product/create'
    | '/api/auth/$'
    | '/_dashboard/bundle/'
    | '/_dashboard/category/'
    | '/_dashboard/product/'
    | '/_dashboard/profile/'
    | '/_dashboard/user/'
    | '/_dashboard/product/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  ApiUploadRoute: typeof ApiUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/user/': {
      id: '/_dashboard/user/'
      path: '/user'
      fullPath: '/user/'
      preLoaderRoute: typeof DashboardUserIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/profile/': {
      id: '/_dashboard/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof DashboardProfileIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/product/': {
      id: '/_dashboard/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof DashboardProductIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/category/': {
      id: '/_dashboard/category/'
      path: '/category'
      fullPath: '/category/'
      preLoaderRoute: typeof DashboardCategoryIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/bundle/': {
      id: '/_dashboard/bundle/'
      path: '/bundle'
      fullPath: '/bundle/'
      preLoaderRoute: typeof DashboardBundleIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard/product/create': {
      id: '/_dashboard/product/create'
      path: '/product/create'
      fullPath: '/product/create'
      preLoaderRoute: typeof DashboardProductCreateRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_dashboard/product/edit/$id': {
      id: '/_dashboard/product/edit/$id'
      path: '/product/edit/$id'
      fullPath: '/product/edit/$id'
      preLoaderRoute: typeof DashboardProductEditIdRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardProductCreateRoute: typeof DashboardProductCreateRoute
  DashboardBundleIndexRoute: typeof DashboardBundleIndexRoute
  DashboardCategoryIndexRoute: typeof DashboardCategoryIndexRoute
  DashboardProductIndexRoute: typeof DashboardProductIndexRoute
  DashboardProfileIndexRoute: typeof DashboardProfileIndexRoute
  DashboardUserIndexRoute: typeof DashboardUserIndexRoute
  DashboardProductEditIdRoute: typeof DashboardProductEditIdRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardProductCreateRoute: DashboardProductCreateRoute,
  DashboardBundleIndexRoute: DashboardBundleIndexRoute,
  DashboardCategoryIndexRoute: DashboardCategoryIndexRoute,
  DashboardProductIndexRoute: DashboardProductIndexRoute,
  DashboardProfileIndexRoute: DashboardProfileIndexRoute,
  DashboardUserIndexRoute: DashboardUserIndexRoute,
  DashboardProductEditIdRoute: DashboardProductEditIdRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  ApiUploadRoute: ApiUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
